[package]
name = "ctags-query"
version = "0.1.1"
authors = ["Matt Snider <matt.snider@protonmail.com>"]
description = "A tool to query ctags with simple boolean expressions."
publish = false
edition = "2018"

[dependencies]
getopts = "0.2"
